// Command opcodegen generates Parse implementations for OBS opcode structs.
//
// A struct marked with a `//obscodegen:decode` comment gets a
// decodeInto<Name>(v *<Name>, d map[string]any) error function generated for
// it, built directly from its fields' `json` tags. If the struct also
// declares a GetOp() method elsewhere in the package (i.e. it's a real
// incoming OpCode, not just a nested payload like Authentication), a
// Parse(opCode *ObsOpcode) error method is generated too, delegating to
// decodeInto<Name>.
//
// Fields without `,omitempty` are required: decoding fails if the key is
// missing or the wrong type. `,omitempty` fields are read only if present.
// Supported field kinds: string, int (JSON numbers decode as float64), and
// pointer-to-marked-struct (recurses one level via the nested struct's own
// decodeInto function).
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strings"
)

const (
	markerComment = "obscodegen:decode"
	sourceFile    = "opcodes.go"
	outputFile    = "opcodes_gen.go"
)

type structField struct {
	goName   string
	jsonKey  string
	optional bool
	kind     string // "string", "int", "struct"
	nested   string // struct type name, when kind == "struct"
}

type structInfo struct {
	name     string
	fields   []structField
	hasGetOp bool
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "opcodegen:", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, sourceFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parsing %s: %w", sourceFile, err)
	}

	structs := collectStructs(file)
	getOpTypes := collectGetOpReceivers(file)

	var marked []string
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			if _, ok := ts.Type.(*ast.StructType); !ok {
				continue
			}

			doc := ts.Doc
			if doc == nil {
				doc = gd.Doc
			}

			if hasMarker(doc) {
				marked = append(marked, ts.Name.Name)
			}
		}
	}

	var infos []structInfo
	for _, name := range marked {
		info, err := buildStructInfo(name, structs)
		if err != nil {
			return err
		}
		info.hasGetOp = getOpTypes[name]
		infos = append(infos, info)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by opcodegen; DO NOT EDIT.\n\n")
	buf.WriteString("package obs\n\n")
	buf.WriteString("import \"fmt\"\n\n")

	for _, info := range infos {
		writeDecodeInto(&buf, info)
		if info.hasGetOp {
			writeParse(&buf, info)
		}
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}

	if err := os.WriteFile(outputFile, out, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputFile, err)
	}

	return nil
}

func collectStructs(file *ast.File) map[string]*ast.StructType {
	structs := map[string]*ast.StructType{}

	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			if st, ok := ts.Type.(*ast.StructType); ok {
				structs[ts.Name.Name] = st
			}
		}
	}

	return structs
}

func collectGetOpReceivers(file *ast.File) map[string]bool {
	types := map[string]bool{}

	for _, decl := range file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Recv == nil || len(fd.Recv.List) != 1 || fd.Name.Name != "GetOp" {
			continue
		}

		switch t := fd.Recv.List[0].Type.(type) {
		case *ast.StarExpr:
			if id, ok := t.X.(*ast.Ident); ok {
				types[id.Name] = true
			}
		case *ast.Ident:
			types[t.Name] = true
		}
	}

	return types
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}

	for _, c := range cg.List {
		if strings.Contains(c.Text, markerComment) {
			return true
		}
	}

	return false
}

func buildStructInfo(name string, structs map[string]*ast.StructType) (structInfo, error) {
	st, ok := structs[name]
	if !ok {
		return structInfo{}, fmt.Errorf("marked type %s: struct not found", name)
	}

	info := structInfo{name: name}

	for _, f := range st.Fields.List {
		if len(f.Names) == 0 || f.Tag == nil {
			continue
		}

		goName := f.Names[0].Name
		tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`"))
		jsonTag := tag.Get("json")
		if jsonTag == "" || jsonTag == "-" {
			continue
		}

		parts := strings.Split(jsonTag, ",")
		jsonKey := parts[0]

		optional := false
		for _, opt := range parts[1:] {
			if opt == "omitempty" {
				optional = true
			}
		}

		kind, nested, err := fieldKind(f.Type, structs)
		if err != nil {
			return structInfo{}, fmt.Errorf("%s.%s: %w", name, goName, err)
		}

		info.fields = append(info.fields, structField{
			goName:   goName,
			jsonKey:  jsonKey,
			optional: optional,
			kind:     kind,
			nested:   nested,
		})
	}

	return info, nil
}

func fieldKind(expr ast.Expr, structs map[string]*ast.StructType) (kind, nested string, err error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", "", nil
		case "int":
			return "int", "", nil
		}
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			if _, ok := structs[id.Name]; ok {
				return "struct", id.Name, nil
			}
		}
	}

	return "", "", fmt.Errorf("unsupported field type %s", exprString(expr))
}

func exprString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// label turns a struct name into the lowercase error-message prefix used
// throughout obs, e.g. "HelloOp" -> "hello op", "Authentication" -> "authentication".
func label(name string) string {
	l := name
	if trimmed, ok := strings.CutSuffix(l, "Op"); ok {
		l = trimmed + " op"
	}

	return strings.ToLower(l[:1]) + l[1:]
}

func writeDecodeInto(buf *bytes.Buffer, info structInfo) {
	fmt.Fprintf(buf, "func decodeInto%s(v *%s, d map[string]any) error {\n", info.name, info.name)

	for _, f := range info.fields {
		writeField(buf, info, f)
	}

	buf.WriteString("\treturn nil\n}\n\n")
}

func writeField(buf *bytes.Buffer, info structInfo, f structField) {
	lbl := label(info.name)

	switch f.kind {
	case "string", "int":
		assertType := "string"
		convert := ""
		if f.kind == "int" {
			assertType = "float64"
			convert = "int"
		}

		if f.optional {
			fmt.Fprintf(buf, "\tif raw, ok := d[%q]; ok {\n", f.jsonKey)
			fmt.Fprintf(buf, "\t\tval, ok := raw.(%s)\n", assertType)
			fmt.Fprintf(buf, "\t\tif !ok {\n\t\t\treturn fmt.Errorf(%q)\n\t\t}\n", lbl+": invalid "+f.jsonKey)
			if convert != "" {
				fmt.Fprintf(buf, "\t\tv.%s = %s(val)\n", f.goName, convert)
			} else {
				fmt.Fprintf(buf, "\t\tv.%s = val\n", f.goName)
			}
			buf.WriteString("\t}\n")
		} else {
			fmt.Fprintf(buf, "\tval%s, ok := d[%q].(%s)\n", f.goName, f.jsonKey, assertType)
			fmt.Fprintf(buf, "\tif !ok {\n\t\treturn fmt.Errorf(%q)\n\t}\n", lbl+": missing or invalid "+f.jsonKey)
			if convert != "" {
				fmt.Fprintf(buf, "\tv.%s = %s(val%s)\n", f.goName, convert, f.goName)
			} else {
				fmt.Fprintf(buf, "\tv.%s = val%s\n", f.goName, f.goName)
			}
		}
	case "struct":
		if f.optional {
			fmt.Fprintf(buf, "\tif raw, ok := d[%q]; ok {\n", f.jsonKey)
			fmt.Fprintf(buf, "\t\tm, ok := raw.(map[string]any)\n")
			fmt.Fprintf(buf, "\t\tif !ok {\n\t\t\treturn fmt.Errorf(%q)\n\t\t}\n", lbl+": invalid "+f.jsonKey)
			fmt.Fprintf(buf, "\t\tnested := &%s{}\n", f.nested)
			fmt.Fprintf(buf, "\t\tif err := decodeInto%s(nested, m); err != nil {\n\t\t\treturn err\n\t\t}\n", f.nested)
			fmt.Fprintf(buf, "\t\tv.%s = nested\n", f.goName)
			buf.WriteString("\t}\n")
		} else {
			fmt.Fprintf(buf, "\traw%s, ok := d[%q]\n", f.goName, f.jsonKey)
			fmt.Fprintf(buf, "\tif !ok {\n\t\treturn fmt.Errorf(%q)\n\t}\n", lbl+": missing "+f.jsonKey)
			fmt.Fprintf(buf, "\tm%s, ok := raw%s.(map[string]any)\n", f.goName, f.goName)
			fmt.Fprintf(buf, "\tif !ok {\n\t\treturn fmt.Errorf(%q)\n\t}\n", lbl+": invalid "+f.jsonKey)
			fmt.Fprintf(buf, "\tnested%s := &%s{}\n", f.goName, f.nested)
			fmt.Fprintf(buf, "\tif err := decodeInto%s(nested%s, m%s); err != nil {\n\t\treturn err\n\t}\n", f.nested, f.goName, f.goName)
			fmt.Fprintf(buf, "\tv.%s = nested%s\n", f.goName, f.goName)
		}
	}
}

func writeParse(buf *bytes.Buffer, info structInfo) {
	fmt.Fprintf(buf, "func (v *%s) Parse(opCode *ObsOpcode) error {\n", info.name)
	fmt.Fprintf(buf, "\treturn decodeInto%s(v, opCode.D)\n", info.name)
	buf.WriteString("}\n\n")
}
