// Code generated by opcodegen; DO NOT EDIT.

package obs

import "fmt"

func decodeIntoHelloOp(v *HelloOp, d map[string]any) error {
	valObsStudioVersion, ok := d["obsStudioVersion"].(string)
	if !ok {
		return fmt.Errorf("hello op: missing or invalid obsStudioVersion")
	}
	v.ObsStudioVersion = valObsStudioVersion
	valObsWebsocketVersion, ok := d["obsWebSocketVersion"].(string)
	if !ok {
		return fmt.Errorf("hello op: missing or invalid obsWebSocketVersion")
	}
	v.ObsWebsocketVersion = valObsWebsocketVersion
	valRPCVersion, ok := d["rpcVersion"].(float64)
	if !ok {
		return fmt.Errorf("hello op: missing or invalid rpcVersion")
	}
	v.RPCVersion = int(valRPCVersion)
	if raw, ok := d["authentication"]; ok {
		m, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("hello op: invalid authentication")
		}
		nested := &Authentication{}
		if err := decodeIntoAuthentication(nested, m); err != nil {
			return err
		}
		v.Authentication = nested
	}
	return nil
}

func (v *HelloOp) Parse(opCode *ObsOpcode) error {
	return decodeIntoHelloOp(v, opCode.D)
}

func decodeIntoAuthentication(v *Authentication, d map[string]any) error {
	valSalt, ok := d["salt"].(string)
	if !ok {
		return fmt.Errorf("authentication: missing or invalid salt")
	}
	v.Salt = valSalt
	valChallenge, ok := d["challenge"].(string)
	if !ok {
		return fmt.Errorf("authentication: missing or invalid challenge")
	}
	v.Challenge = valChallenge
	return nil
}

func decodeIntoIdentifiedOp(v *IdentifiedOp, d map[string]any) error {
	valNegotiatedRpcVersion, ok := d["negotiatedRpcVersion"].(float64)
	if !ok {
		return fmt.Errorf("identified op: missing or invalid negotiatedRpcVersion")
	}
	v.NegotiatedRpcVersion = int(valNegotiatedRpcVersion)
	return nil
}

func (v *IdentifiedOp) Parse(opCode *ObsOpcode) error {
	return decodeIntoIdentifiedOp(v, opCode.D)
}
